### ISSUE TITLE
Write consent forms for early tests

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#1]
When we present patients with the choice to participate in their app, should we be asking for permission to share their eligibility info with a network of safety-net providers, or with each provider individually? If a network, how should we handle the addition of new providers?

**Comment by mapsam** [comment]
This seems like a great question for Danny. Let's make sure we bring it up in our discussion on Friday the 27th.

**Comment by bengolder** [comment]
Update: We discussed HIPAA implications of our current non-client facing app, and it seems like the use of the app by clinics would fall under a BA agreement and general consent clauses about sharing patient info for billing and care coordination purposes. My current assumptions:
- we probably don't need a consent form that is specific to our app, because we are currently covered by general consent forms used by clinics during intake.
- We might need BA agreements with clinics (not sure about this)?
- Given that some clinics provide behavioral health services, we may need to exclude content regarding behavioral health, because it requires more strict authorization steps. Or if we do include it, we would need to look at authorization steps for patients.

**Comment by andreasRVA** [comment]
We will probably need to get the basic permission, waiver, contracts assigned for the patient, CHW, and the approved healthcare providers as well. I am not sure who should be the bearer or these contracts and such but we should outline these areas before we get too far along as they are vital for the data being collected and shared and making sure its protected, safe and controlled. Does CfA have legal support in this arena or will this need to be a RCHD/Virginia process?

**Comment by bengolder** [comment]
@andreasRVA Yes, we have a lawyer that specializes in HIPAA that we consulted about two weeks ago. We will talk with her again to clarify assumptions and possibly draft a privacy policy. Here's the relevant section in HIPAA that she pointed us to: https://www.law.cornell.edu/cfr/text/45/164.506

**Comment by mapsam** [comment]
For record's sake and updating @andreasRVA, we've decided to continue production under the "umbrella consent" concept, where you will have access to all patients in the system if you are a standard user. It opens the door for more tiered user roles (#173) moving forward, and removes an unnecessary amount of friction for the users and patients that the app's sharing/consent process created.

We heard from Fairfax that they are running their app in under this umbrella process that allows for partners to be added and BAs to be updated annually (?) with newly added care providers between Inova and the county.

How do early consent forms change with this? What officially needs to be written for us to start testing?
- [ ] Patient consent to the application – paper and app
- [ ] Business agreement between all active partners (including the Richmond City Health Department) – paper
- [ ] BA between CfA and the partnership – paper

**Comment by mapsam** [comment]
**UPDATE**

We are in progress of getting BAA's signed between the city and the following partners to prepare for testing before the end of the fellowship:
- [ ] Daily Planet
- [ ] Access Now
- [ ] Bon Secours Care-a-van
- [ ] Richmond Center for High Blood Pressure
- [ ] OAR
- [ ] Resource Centers
- [ ] Code for America

Patient consent form AND BAA have been approved on Code for America's end. They are attached here as PDFs. 

[RVA_PatientConsentv0.2.pdf](https://github.com/codeforamerica/rva-screening/files/3942/RVA_PatientConsentv0.2.pdf)

[RVA_BAAv0.1.pdf](https://github.com/codeforamerica/rva-screening/files/3941/RVA_BAAv0.1.pdf)

**Comment by andreasRVA** [comment]
Sam

I think we should draft a review statement of the Patient Consent form to
be read to the patient to summarize the document. Something along the lines
of:

By signing this document you agree
1. That all information provided is accurate and truthful
2. Agree to share this information with the Richmond Community Health
Partners
3. And that the Richmond Community Health Partners are able to share this
information among themselves for the benefit of providing financial
screening for your access to their services
4. I can refuse and/or cancel this authorization to my provided information
at any time, and if I  refuse, I understand that this will have no impact
or effect on my access to the services provided by the RCH Partners.

Something along those lines should suffice. A way for the basic elements to
be outlined in a 5th grade equivalent language is important. Thoughts?

Andreas

On Mon, Oct 26, 2015 at 7:06 PM, Sam Matthews notifications@github.com
wrote:

> Closed #1 https://github.com/codeforamerica/rva-screening/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/rva-screening/issues/1#event-446175774
> .

## 

Andreas D. Addison
Civic Innovator, City of Richmond
804.833.5898 c
twitter         @andreasrva
facebook     andreasrva
GovLoop     Andreas Addison
Skype         andreasRVA

**Comment by mapsam** [comment]
I like it - does this go on to the actual document? Where do you think would work best?

**Comment by andreasRVA** [comment]
I'm thinking this is part of the operational training for use in the field. Part of the on boarding process for new patients as read to them by the trained and qualified input coordinator from the RCH Partners. 

Best,
Andreas D. Addison
Civic Innovator, City of Richmond
804.833.5898

Please excuse autocorrect typos as this was sent with my thumbs from my iPhone

**Comment by andreasRVA** [comment]
I would recommend making the following changes to the BAA and MOU section:

The Richmond Community Health Partners network is initiated through a Business Associate Agreement (BAA) between the Richmond City Health District and Code for America that establishes the access and utilization of the QuickScreen application and ensures its compliance with HIPAA. The Richmond Community Health Partners are granted access to the application through the Memorandum of Understanding (MOU) drafted between the application owner ____ and each of the consenting partners. These documents assure that the data and information entered, stored and shared through the application is secure and safe and only accessible by approved, trained and qualified users.
