### ISSUE TITLE
FEATURE: First Clinic - Assisted

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#10]
We are going to prototype the **First Clinic - Assisted** process as a simple application in Flask. There are no plans to build user accounts at this point, but rather prototyping the `CREATE` functionality of a "patient" in the database. We'd also like to start exploring the document upload process. Some goals for this feature pathway:
- [x] Create new client (row in `clients` table)
- [x] Enter client information (name, birthday, income, etc.)
- [x] Add new document
- [x] simple UI design - start thinking about a framework for front-end testing (i.e. Gulp)

Our intention with this process is to start the discussion on our database schema and to give ourselves a framework to begin the UI design process.

@esmithayer is taking the lead and putting together the first two goals with a single table, sqlite Flask install and we'll go from there.

**Comment by esmithayer** [comment]
We have all of these things!

**Comment by mapsam** [comment]
:+1:
