### ISSUE TITLE
What is the best way to handle gender options?

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#100]
User seemed curious about the male/female/transgender portion. User said they were seeing the transgender option on forms more often these days. When they entered “female” or “male” they wondered if having the transgender dropdown continue to exist was necessary? Could we combine these questions, or make them conditional?

**Comment by bengolder** [comment]
Here is the field in both forms:
Access now:
![screen shot 2015-05-19 at 9 45 21 am](https://cloud.githubusercontent.com/assets/451510/7708638/e516a136-fe0b-11e4-83dc-9d965e95ffa8.png)
Daily Planet:
![screen shot 2015-05-19 at 9 45 40 am](https://cloud.githubusercontent.com/assets/451510/7708639/e518d4c4-fe0b-11e4-9a86-20622d908e72.png)

The abbreviations aren't clear and Access Now's screener was not aware that it was a transgender option, (she thought it was asking gender in Spanish).

**Comment by bengolder** [comment]
I think we should leave it for now, and consult with someone with more experience on presenting gender options in forms.

**Comment by bengolder** [comment]
This should probably be addressed in a similar manner to #101 and #113.

How should confusing eligibility questions be dealt with?
