### ISSUE TITLE
Linking patient accounts

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#104]
This came up in user testing and conversations with our partners.

**Under parent's insurance:** Some people are under other people’s insurances (such as children and young adults). They typically don’t have a card to prove this, but it would be interesting to link to a parent’s account if they uploaded their information previously.

AND

**Questions from city partners:** 
- How does it work if a child is being screened? Do they typically get their own account or are they linked in through a parent’s account? 
- How can we link spouses?
- How can we link families/partners/anybody?

**Comment by bengolder** [comment]
One possibility is to have "Household" models, and to allow people to be added and taken away from households. In this case, we would still want to have a simple form for household members that doesn't require extra steps, and we should think through the process of adding a person who's household members do exist, and adding someone who has some household members that aren't in the system.

We should double check if there are any greater privacy or consent requirements for children, as well as if there are any concerns about collecting PII on people who aren't patients.

**Comment by mapsam** [comment]
That's definitely the approach I'm thinking of. What if you when you filled out the household table, if that patient didn't exist, it creates a new patient in the database? Probably some privacy issues there, but worth thinking about.

**Comment by bengolder** [comment]
I realized that this is also a question we should escalate out to partners. How do they currently deal with this situation?
