### ISSUE TITLE
Progress calculation

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#105]
How do we do it? What is it called?

In user testing, this random percentage didn't mean much :stuck_out_tongue_closed_eyes:

**Comment by mapsam** [comment]
I've added "completion" to the percentage for testing but would still like to discuss how we calculate percentage. Some questions to ask during user testing
- "is showing that percentage useful?" 
- "how would you want to summarize completion?" - warrants a version without the percentage as to not force the idea on them
- "what would your reaction be to a patient with low completion percentage? Would you help them fill out their profile more thoroughly?"

**Comment by bengolder** [comment]
Another way to phrase the question:
"What would you want to know about a patient's progress through different applications, and what would you do with it?"

**Comment by mapsam** [comment]
yes! Nice!

**Comment by mapsam** [comment]
recorded in future development docs
