### ISSUE TITLE
Patient referral notifications

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#106]
User liked the simplicity of "sharing info" buttons, but was wondering if there was another way to confirm that the information has been sent. Would an email suffice? How about just showing that the history has been updated on a patient?

Sometimes patients tell user they didn’t receive things, and user wants to be able to check that they did actually do them.

**Comment by bengolder** [comment]
We should definitely have a type of log in history that is exclusively about sharing. Who shared which patient with whom.

> Sometimes patients tell user they didn’t receive things, and user wants to be able to check that they did actually do them.

This sounds like it gets at referral tracking. In an email or message to another provider, we could have them click a link to the patient details page, and log that they accessed it.

**Comment by esmithayer** [comment]
We have a referral/screening result history now, which shows whether referrals have been received, so updating the issue title to focus on the notification piece.

**Comment by mapsam** [comment]
We now have emails notifying users/clinics when referrals are made - can this issue be closed for more specific ones down the road?

**Comment by mapsam** [comment]
recorded other forms of notifications could exist in our future development docs
