### ISSUE TITLE
Add service calculations in prescreener for Resource Centers

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#108]
We were handed the sliding-scale calculation sheet at the Resource Centers while user testing. These show ranges of income (week, month, year) and the percentage of the cost a patient owes. Looks like all is based on the FPL guidelines starting at $11,770 for 1 person at 100% FPL. 

"majority of the state":

![img_0263](https://cloud.githubusercontent.com/assets/1943001/7703630/371018b4-fe07-11e4-8393-5ca113955469.jpg)

"northern Virginia"
![img_0264](https://cloud.githubusercontent.com/assets/1943001/7703666/806beaba-fe07-11e4-9328-42189c424842.jpg)

**Comment by bengolder** [comment]
Is there a formula behind this?

**Comment by mapsam** [comment]
It's ALL based on that base $11,770 (a la FPLAPI) and the number 52 (weeks in a year). Mostly a reference sheet for CHWs.

The piece that is unique to the Resource Centers is the percentage coverage gaps that patients fall within their sliding scale payments.

**Comment by mapsam** [comment]
In regards to the "Northern VA" - I'm honestly not sure what the calculation difference is there.
