### ISSUE TITLE
Pre-screener calculation error

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#109]
Got an error with user in the pre-screener calculations. User had all four services selected and the following options filled out:

![screen shot 2015-05-19 at 11 34 55 am](https://cloud.githubusercontent.com/assets/1943001/7708032/136d9958-fe21-11e4-9ca6-50f95ccef4de.png)

Error:

![screen shot 2015-05-19 at 11 34 50 am](https://cloud.githubusercontent.com/assets/1943001/7708070/535c0752-fe21-11e4-97a4-d6148ff4eecc.png)

**This only happens when the household number is `4` or greater**

**Comment by esmithayer** [comment]
Fixed!
