### ISSUE TITLE
Difference between race and ethnicity fields is confusing

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#113]
Several users have mentioned that people won't know what race to select for a Latino patient and that it should just be one field. But I think the way we have it currently has to do with FQHC reporting requirements, so we should research what makes the most sense.

**Comment by bengolder** [comment]
Definitely agree. This and others should maybe be tagged as issues with the paper forms.

**Comment by mapsam** [comment]
Agreed on this one.

**Comment by bengolder** [comment]
I think this question should be addressed in a similar manner to #101.

The user need is how assisters can mark confusing questions for administrators and screeners, and possibly get help with answering them.

Should we make some non-functioning page prototypes that show some possible workflows for this, and then talk to assisters, screeners, and administrators to determine how useful it would be?

Some possible examples: 
- (Assister) patient details page --> help page for question --> button to ask a question about the question
- (Screener) service account page --> Qs that people are having trouble with, Qs about questions --> Editable help page for question (perhaps with Q&A format)
- (Administrator) Service account page --> see which questions are confusing/troublesome --> see which other services include this question on their eligibility forms
