### ISSUE TITLE
Users aren't sure what "personal documents" means

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#114]
Several users initially didn't know what this was intended for. They suggested a label saying something like "Example: pay stubs" or having a dropdown of common document types.

**Comment by bengolder** [comment]
The section header could probably be clearer as "Document Uploads" rather than "Personal Documents"

**Comment by esmithayer** [comment]
Looks like that commit just changed "Personal Documents" to "Document Uploads"? Let's leave this open if so, to consider an explanatory label or document type dropdown like users suggested. I think the issue was more that they didn't know what kinds of documents they were supposed to add, not that they didn't understand the uploading piece.

**Comment by bengolder** [comment]
Thanks for clarifying!

**Comment by bengolder** [comment]
I would propose that for the time being, we either:
1. Add copy to give examples of the kinds of documents we expect
2. add a "document type" dropdown that contains common types of documents (perhaps with an "other" option)
