### ISSUE TITLE
Add more information about calculation to prescreening result page

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#116]
Users wanted to know what the patient's FPL percentage was and what the criteria were that led to the result, so that they can explain it clearly to the patient (particularly if the patient doesn't qualify).

**Comment by mapsam** [comment]
This also touches the possibility of showing the calculations as a _sidebar_ or something on the patient details page. Once a patient is already in the system with the necessary information for calculating, why not show some quick possibilities without having to pre-screen every time?
