### ISSUE TITLE
Add FPL percentage calculation to patient details page?

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#117]
Users wanted to see the calculation result after adding household members and income sources.

**Comment by bengolder** [comment]
:+1: I think this is a great idea

**Comment by bengolder** [comment]
For now, the version I made just adds FPL to the page but does not implement a dynamic update of the FPL figure using javascript. I think we should look into some more general patterns for updating the page based on form input.

**Comment by mapsam** [comment]
Agreed - your solution seems great for now, though!

**Comment by bengolder** [comment]
reopening to think about this in terms of databinding

**Comment by esmithayer** [comment]
Going to close this and make a broader issue about dynamic updates to the patient details page.
