### ISSUE TITLE
Dynamically update "patient" row in household members table when patient name is updated

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#118]
Just having the row say "Patient" until the form is saved confuses users, and they often add the patient again.

**Comment by bengolder** [comment]
A data binding example that might address this:

![data_binding](https://cloud.githubusercontent.com/assets/451510/7762214/ff107cb6-ffe5-11e4-86cb-469d87573985.gif)

**Comment by esmithayer** [comment]
Closing this since #166 includes it.
