### ISSUE TITLE
Prescreen service selection is unclear

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#119]
User's weren't aware they could select multiple services or organizations to screen for. We could also have a "select all" option?

Or possibly default to all selected, which answers both of these.

**Comment by bengolder** [comment]
I like defaulting to all selected for now.

**Comment by mapsam** [comment]
I've added checking to default, but @esmithayer brings up a great observation:

> Do we need to allow for checking/unchecking? What if we just show everything and remove a route?

@esmithayer feel free to correct me if that statement is incorrect :stuck_out_tongue_winking_eye:

**Comment by bengolder** [comment]
Why not simplify? I like it.
