### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#121]
Heroku gives us Postgres, so it would probably be a good idea to use databases for local dev that roughly match the environment in production. I made this switch myself while testing the deployment branch, and there were no difficulties in switching.

Steps to switch:
### 1. make sure PostgreSQL is installed.

The easiest is probably [Postgres.app](http://postgresapp.com/). Alternatively, you can install it with Homebrew: `brew install postgres`. [Heroku is running version 9.4.1](https://postgres.heroku.com/databases/demo-screener-database).
### 2. create a database for the app.

If you installed Postgres with Homebrew, or [you've added the path to
Postgres.app scripts to your `.bash_profile`](http://postgresapp.com/documentation/cli-tools.html), you can make a database with

```
createdb screener
```

Alternatively, you can run psql scripts to setup the database

```
create database screener;
```
### 3. edit or create a `.env` file

Add the following setting to your `.env` file, in the root folder of the repo:

```
DATABASE_URL='postgresql://localhost/screener'
```

If you have any permissions issues accessing the database, you can designate a
specific user and password in your `DATABASE_URL` setting:

```
DATABASE_URL='postgresql://myusername:mypassword@localhost/screener'
```
### 4. recreate the tables

`cd` into the root folder of the repo, and run

```
make new_db
```
### 5. Add user account

```
python add_user.py
```
### 6. [optional] Add mock data

if #127 is merged, we can just run this command to add a bunch of patients to the db

```
python add_mock_data.py
```

**Comment by mapsam** [comment]
I'm going to pull myself out of the running here, mostly because I don't know much about db's and would like to hear from @esmithayer. 

It seems proper to work with the same db as our production, though. Thanks for outlining this @bengolder!

**Comment by esmithayer** [comment]
I think we've all done this now, right?
