### ISSUE TITLE
Comma in number field leaves cryptic error

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#123]
When the user entered a number with a comma, the following error appeared on chrome:

![screen shot 2015-05-20 at 8 46 16 am](https://cloud.githubusercontent.com/assets/1943001/7725936/e84edc4e-fecc-11e4-91b4-67fb446c66a2.png)

The user thought they had entered a number properly, and was confused by this error. I wonder if we can remove commas programmatically?

**Comment by bengolder** [comment]
This is in the HTML. It is the automatic browser validation based on the type of field. For example, if you entered an invalid email into an `<input type="email">`, the browser would show the same message.

**Comment by mapsam** [comment]
Yup, that's what I figured. If we go through with turning this into a text field via #126 I think it should solve the issue.
