### ISSUE TITLE
Date fields allow for too many numbers in the year section

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#125]
![rva-screening-datebug](https://cloud.githubusercontent.com/assets/1943001/7726296/ee03edbc-fece-11e4-8b69-175b4e848c2d.gif)

This leads to an error on submit.

**Comment by bengolder** [comment]
Possible fix is to add a max & min attribute: http://stackoverflow.com/a/17292152

**Comment by bengolder** [comment]
We need to make sure with maxes and mins that Jeralean Talley can still fill out our form
![screen shot 2015-05-20 at 6 19 13 pm](https://cloud.githubusercontent.com/assets/451510/7739823/d3c7963a-ff1c-11e4-982b-cb021eae7d5a.png)

**Comment by mapsam** [comment]
oh my god
