### ISSUE TITLE
Dollar fields should be prefixed with dollar sign to prevent user from entering the symbol

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#126]
Entering a `$` into the field broke the program.

![screen shot 2015-05-20 at 9 05 17 am](https://cloud.githubusercontent.com/assets/1943001/7726362/74856870-fecf-11e4-97fb-4f426095307f.png)

**Comment by bengolder** [comment]
:+1: good change. We may also want to change this from a number input to a text input that can only take digits, commas, dollar signs, and periods. It should be able to take a dollar sign and commas without having errors.

**Comment by mapsam** [comment]
Would extra characters be removed on the server side if we allowed them?

This relates to #123
