### ISSUE TITLE
Updates to service profile pages

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#135]
### `/service/<id>`

Service profiles will have information about a service (i.e. Daily Planet):
- [x] name
- [x] logo
- [x] description
- [x] website
- [x] contact information (main contact & per location)
- [x] location(s) (potentially a map of locations)
- [ ] services offered
- [ ] hours of operation
- [ ] main contact (associated to a user profile?)
- [x] list of user profiles (not patients!) associated to service
- [ ] number of patients in system associated to this service
- [ ] which services their patients are shared with?
- [ ] next steps to apply/make an appointment

**Comment by mapsam** [comment]
Should some of these options be tied to specific locations? Things such as _hours of operation_, _services offered_, _main contact_ may differ depending on the location. It would be particularly useful especially if someone is trying to reach Fairfield Resource Center to be able to reach that particular phone instead of a general contact for the Resource Centers.

**Comment by esmithayer** [comment]
Yeah, that makes sense. We could have ServiceLocation models that are associated with a single Service.

**Comment by mapsam** [comment]
Here's a screenshot of some of the above information in a profile page:

![screen shot 2015-05-26 at 4 57 55 pm](https://cloud.githubusercontent.com/assets/1943001/7824411/61b34d90-03c8-11e5-91e4-ee1a87a1efd9.png)

As for the locations, I've made it so you can just create a new HTML element in the template with the specific information...

``` HTML
<div class="location" 
     data-name="Cowardin" 
     data-address="108 Cowardin Ave, Richmond, VA 23224"
     data-latitude="37.519541"
     data-longitude="-77.449814">
  <p><strong>Cowardin</strong></p>
  <p><span class="glyphicon glyphicon-home"></span> 108 Cowardin Ave, Richmond, VA 23224</p>
  <p><span class="glyphicon glyphicon-user"></span> <a href="#">Contact Name</a></p>
  <p><span class="glyphicon glyphicon-earphone"></span> <a href="tel:6666666666">(123) 456-7890</a></p>
</div>
```

**Comment by bengolder** [comment]
I think we should also nail down:
1. Who, specifically, do we assume would be using this page?
2. What do we assume they would be trying to do there?

I think we should then put information on here that specifically addresses that user's needs and little else. I'm slightly concerned that this could end up more like a brochure about the service, rather than a page that prioritizes helping someone get a thing done.

I think this is a great first run, however.

**Comment by bengolder** [comment]
Also, should users be linked to one or more locations of a service?

**Comment by bengolder** [comment]
Can we include a mobile sketch?

**Comment by mapsam** [comment]
Updated service profiles now using a temporary `SERVICE_DATA` in `views.py`. @esmithayer feel free to remove this whenever.

![rva-screener-serviceprofiles](https://cloud.githubusercontent.com/assets/1943001/7873617/8056dd7e-0559-11e5-8ac9-1d6a411a6949.gif)

mobile
![rva-screener-serviceprofiles-mobile](https://cloud.githubusercontent.com/assets/1943001/7873671/4374bc4a-055a-11e5-81cd-7b14c05b6e73.gif)

**Comment by mapsam** [comment]
@bengolder in regards to your comments:

> Who, specifically, do we assume would be using this page?

I don't know who else would be using this other than our users, as screeners. Do you have anyone else in mind?

> What do we assume they would be trying to do there?

Probably not much. I see this mostly as an information store. The more important piece is the user profile so users can contact other users about specific patients. Maybe, then, the list of users should be prioritized on this page?

**Comment by bengolder** [comment]
> The more important piece is the user profile so users can contact other users about specific patients. Maybe, then, the list of users should be prioritized on this page?

Totally, that's the kind of thing I was trying to get at. In other words, "What is the user need?" so we can judge the design against the goal of answering that need, and use that need as the thing to test when doing user testing.

For the type of user, I was imagining one or more of the roles defined in the user testing protocol. Or another example if those don't fit.

Sorry if the previous Q's weren't that clear.

**Comment by mapsam** [comment]
Veronica mentioned that it would be helpful to have **hours** on service pages to give to patients.

**Comment by greggish** [comment]
Hi folks - I haven't been following the project all that closely, but i noticed this issue. When it comes to the raw data about services -- things like hours of operation and relationship between services and facilities -- Open Referral has mapped out a specification that may be useful to you in the short term in terms of modeling, and may increase the potential value of your product in the long-term by making it easy to interoperate with 2-1-1s and other systems like Purple Binder et al. [Our data spec is in this repo](https://github.com/codeforamerica/OpenReferral). Happy to answer questions about this, and to think through where it may or may not be useful.

**Comment by mapsam** [comment]
Hey Greg, thanks for the note! We've definitely kept our eyes on Open Referral in regards to service information across Richmond. 

In the app's current state, we are finding that pushing an information spec is difficult and puts us down a lot of rabbit holes. There is so much local knowledge that we want to capture and are thinking that the best way to get it in there right now is to just let people type it out (i.e. in a markdown file) so things can change quickly for the needs of the app.

I'd be interested to hear how Open Referral has thought through capturing this hyper local knowledge. For example: `Location directions saying that the front desk is accessed at the second door down the hallway, not the first` OR `the office used to be on the lower level but has since moved to the third`.

In the long-term, I think integrating 211 and other systems is an excellent idea!

**Comment by greggish** [comment]
Yeah I suspect that the short-term value may be, at a minimum, just a
reference point for your R&D about information types and relationships; at
best, it could be an adaptable model. You may find it helpful simply in
that it reflects the current state of the field -- and, in return, your
feedback around what's missing or painful or whatever may help us improve
the spec in its next iteration.

In the mid- to long-term, the integration prospect is very real: Virginia's
2-1-1 system, for instance, is statewide and they use [iCarol](http://icarol.com), which was one of our lead partners in the design of our
spec. And given momentum in DC and Maryland towards using iCarol for
publishing open resource data (it serves pretty much all of the DC metro
region) Virginia may not be far behind.

As for your question, our spec recognizes separate entities of
organizations, services, and sites -- and includes a description field for
each, which accepts markdown. So while I wouldn't speak authoritatively to
this, I assume that this kind of hyperlocal knowledge can be captured
within it. Meanwhile, I can say that the idea is that people could extend
the spec as they wish, or collect whatever additional data they like to
augment the core elements.

**Comment by mapsam** [comment]
recording this in our future development document, but closing for now
