### ISSUE TITLE
Add service-level permissions to patients

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#137]
Patient details should initially be visible only to users at the service that added the patient. Other services should be able to gain access via a referral from the first service or by clicking through a patient consent form.

**Comment by mapsam** [comment]
@esmithayer I imagine this will require you to work with the `consent/` route - feel free to change that however you want since it was only temporary for testing last week.

**Comment by mapsam** [comment]
@esmithayer this is complete, yes?

**Comment by esmithayer** [comment]
Yup!
