### ISSUE TITLE
Decide on search/browse/add patient workflow

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#138]
Users weren't sure whether the landing page showed all patients in the system or only their patients, and weren't sure what the "Search new patients" button meant (one user said "new" didn't make sense because the patient could have been in the system for years). Once on the search page, they weren't sure how "Add new patient" on a patient entry was different from "add patient" in the nav bar.

**Comment by mapsam** [comment]
What if we have a dropdown on the main navigation that includes both options, instead of forcing the user through their own patients to add a new one?

![screen shot 2015-05-27 at 9 11 12 am](https://cloud.githubusercontent.com/assets/1943001/7838029/6323fbe2-0450-11e5-8246-28d42a1579be.png)

It also now seems confusing to have the "add patient" main navigation. It might make more sense to say "create new patient"?

![screen shot 2015-05-27 at 9 13 13 am](https://cloud.githubusercontent.com/assets/1943001/7838084/a08dc18e-0450-11e5-934b-080ad2f121c8.png)

**Comment by esmithayer** [comment]
I like the idea of adding it to the nav bar, but is there space for them to be two separate buttons? The dropdown would add an extra click for users to get to the "Your Patients" page, and that might be something they're doing frequently.

Agreed that "Create Patient" is more clear than "Add Patient". How about something like "Other Patients in Network" instead of "New Patients"? And once we have users associated with services, we could do "[service]'s Patients" instead of "Your Patients" to make clear that the permissions are service-level and not user-level.

**Comment by bengolder** [comment]
Here are the assumed use cases I believe we are discussing:
1. A user (screener or assister) believes that a patient is not in the app and wants to create a record for that patient immediately. _"Create/Add Patient"_
2. A user (screener or assister) wants to know if a patient is already linked to another service in the app. If the patient is linked to another service, link them to the user's own service. If the patient does not exist, add them to the app, linked to the user's own service. _"Explore New Patients"_
3. A screener or assister wants to find someone who they believe is already in the app and tied to their own service _"Browse Your Patients"_

Cases 1 & 2 are related. If you were going to add a patient to the app, you'd want it to tell you if the patient happens to be already linked to other services. If you thought a patient might be linked to another service but they weren't, you'd want to add them to the app. 

Maybe what we need is a _"New Patient"_ page that allows you to quickly enter ID information for a patient. If the ID info matches an existing entry it allows you to link it to your service (or just takes you to the patient's details if they are already linked). If the ID info doesn't match any existing accounts, then it creates a new patient record.

**Comment by mapsam** [comment]
After a discussion this morning we have two upcoming iterations for this issue.

First, for the sake of time and the upcoming user testing, we will execute a quick update to language and navigation that clearly identifies the user's available actions. This involves renaming some of the "actions", including `Create new patient`, `Find a patient`, and `View your patients`. 

Secondly, an update to the user addition pathway will be necessary. The proposed processes are `view patient` and `add patient`. Viewing patients will be _your_ patients, while adding a patient will be either existing in network OR completely new in database. When adding a new patient, the user will enter name and DOB (specifics are undefined) and execute a "search" through some confirmation. Then the patient is either **a)** created in the database OR **b)** shows up as existing in the network where the user requests permission to view patient details.

**Comment by mapsam** [comment]
Here is a quick first update. Thoughts? Does this clearly define the specific actions?

![screen shot 2015-06-01 at 5 22 34 pm](https://cloud.githubusercontent.com/assets/1943001/7926138/e5eaf61c-0882-11e5-9078-2e7e10dc1faf.png)

**Comment by bengolder** [comment]
I think that's clearer

**Comment by mapsam** [comment]
Would it be worth adding some extra description text to the pages? Such as:

![screen shot 2015-06-01 at 5 39 27 pm](https://cloud.githubusercontent.com/assets/1943001/7926288/324427a2-0885-11e5-8494-a95db1e77acd.png)

**Comment by bengolder** [comment]
Yes, I think that's helpful

**Comment by esmithayer** [comment]
"Find Patients" with the search icon seems like it could also refer to searching your own service's patients. Is there anything concise that will convey the difference? "Find Patients in Network"? Just "Patients in Network"?

The description text seems like a bit much to me--testing with that might prevent us from figuring out whether the nav bar labels would work on their own.

**Comment by mapsam** [comment]
Truth - "Find new patient" or "Find patient in network" seems good to me.

Totally fine holding off on the description text. But good to remember we can always incorporate safety net alerts!

**Comment by mapsam** [comment]
Updated network language:

![screen shot 2015-06-01 at 6 50 19 pm](https://cloud.githubusercontent.com/assets/1943001/7927018/17d8bc48-088f-11e5-9860-3756e5ff76a6.png)

**Comment by mapsam** [comment]
The above, with "Find Patient in Network" has been merged into `master` in #154. Going to keep this issue open for the second iteration.

**Comment by mapsam** [comment]
Per discussion in codeforamerica/rva-screening-ui-prototypes/issues/18 we have decided to include search and view patients in the same page. Search is also the first action taken, before creating a patient - in order to more effectively prevent duplicate entries of patients.

This effectively removes the menu items for "Create Patient".

**Comment by mapsam** [comment]
Resolved in #179
