### ISSUE TITLE
How should FPL be calculated?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#15]
This is a sub-issue of #14. Most of the space on eligibility forms is taken up with questions that try to get at calculating FPL (income / household size). This is perhaps the most complicated portion of most applications. There are questions that try to map out everyone involved in the household, their sources of income, and who can be listed as a dependent to whom. There are detailed questions about many different types of income. The questions about income types have implications about which documents should be included as proof of income.

**Comment by bengolder** [comment]
Talked with a friend who said that when she applies, one of the difficulties is that she is paid sporadically. She might get a paycheck one month and then go 2 more months without a paycheck. This brings up the issue of how to deal with income that is unsteady.

**Comment by bengolder** [comment]
Talked with @lippytak and he said the relevance of questions depends heavily on the population being asked. Should there be different types of worksheets? How should those be segmented, for which populations?

**Comment by bengolder** [comment]
This is an example of a simple FPL form from mRelief:
![mrelief_fpl](https://cloud.githubusercontent.com/assets/451510/7239202/d2485cd6-e75c-11e4-8d3f-8387a908b5e9.gif)

**Comment by bengolder** [comment]
Here's an example from the CalFresh calculator:
![clean_fpl](https://cloud.githubusercontent.com/assets/451510/7239459/e6f048d6-e75e-11e4-8f6a-82467652d914.gif)

**Comment by bengolder** [comment]
Here are examples from Access Now's Universal Screening Form:
![screen shot 2015-04-20 at 1 21 36 pm](https://cloud.githubusercontent.com/assets/451510/7239598/1de2755c-e760-11e4-9bc2-fd4a0bd1d689.png)
![screen shot 2015-04-20 at 1 21 49 pm](https://cloud.githubusercontent.com/assets/451510/7239599/1de2dede-e760-11e4-8f36-b4d101849767.png)

**Comment by bengolder** [comment]
Here are examples of FPL info collection from the Resource Centers
![screen shot 2015-04-20 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/451510/7239808/8d3cb70e-e761-11e4-9734-25c0f2ce0ad0.png)
![screen shot 2015-04-20 at 1 31 56 pm](https://cloud.githubusercontent.com/assets/451510/7239807/8d3a5fcc-e761-11e4-9c1c-60c06f7eb865.png)

**Comment by bengolder** [comment]
### Household Size

In terms of calculating **household size**, the main difference is how each explains the definition of a household member. All seem to overlap substantially with the [Healthcare.gov definition of household members](https://www.healthcare.gov/income-and-household-information/household-size/).

**Access Now** asks for the names and relationships of the patient's family unit living in the house, and if the patient did file taxes last year, persons claimed as dependents by the patient who do not live in their household.

**Daily Planet** and the **Health District Resource Centers** ask for "people the patient is financially responsible for"

The **HealthCare.gov** definition of household member is **"tax filers + tax dependents"**:
- Yourself
- Your spouse (this applies to legally married couples, whether opposite sex or same-sex. Learn more about same-sex couples and the Marketplace.)
- Your children who live with you, even if they make enough money to file a tax return themselves
- Anyone you include on your tax return as a dependent, even if they don’t live with you
- Anyone else under 21 who you take care of and lives with you
- Your unmarried partner, only if one or both of these apply:
  - They're your dependent for tax purposes
  - They're the parent of your child

A few confusing situations I can imagine between these definitions:
- What if you don't file taxes (perhaps because you are under the poverty line) and you have an adult partner or friend who you take care of financially?
- What if you have been staying on the couch of your aunt for the past month and would otherwise be homeless? What if you are the aunt, would you list your niece/nephew?
- Would someone list children that live with them who they don't claim as dependents (important if you want your 19 year old to get financial aid for college)? What if you charge rent to your adult children?
- What if you are 19, living at home, and your parents claim you as a dependent even though you are financially self-sufficient or helping to support them financially?
- What if you are a single parent who has been staying on a friend's couch for the past month and sharing groceries?

**Comment by bengolder** [comment]
### Household Income

There are differences in which types of income are explicitly mentioned. For example, Access Now does not ask for TANF or Food Stamps to be including in income while Daily Planet does. At the Resource Centers, this might fall under "Other welfare benefits". There is also a difference in whether the amounts for each source are added up or simply noted. Should all types of income requested actually be a part of determining household income? Furthermore, if a clinic asks patients to include income that would not be part of a household income determination by HealthCare.gov, should the patient's FPL % actually be lower? Do they ask about assets or liabilities?

[Here are the income sources used](https://www.healthcare.gov/income-and-household-information/income/) by HealthCare.gov.

Here is Access Now's portion that asks about income and sources:
![screen shot 2015-04-23 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/451510/7309120/d598ea5c-e9cf-11e4-831e-e34644e055fa.png)

Daily Planet's income form:
![screen shot 2015-04-23 at 3 45 24 pm](https://cloud.githubusercontent.com/assets/451510/7309131/ea2d1a56-e9cf-11e4-8ff4-c2cad7a8ea7d.png)

While VCU Financial Assistance asks for income, assets, and liabilities:
![screen shot 2015-04-23 at 3 45 53 pm](https://cloud.githubusercontent.com/assets/451510/7309153/0aa69d34-e9d0-11e4-8732-1a9deb38c6f2.png)
![screen shot 2015-04-23 at 3 46 04 pm](https://cloud.githubusercontent.com/assets/451510/7309154/0f99d16c-e9d0-11e4-8b44-f0ddb3a5cd5d.png)

**Comment by bengolder** [comment]
For pre-screening purposes, it's important to note some of the existing Medicaid/Medicare pre0screening tools that exist. This is the Kaiser Health Insurance Marketplace Calculator:
![screen shot 2015-04-27 at 2 08 34 pm](https://cloud.githubusercontent.com/assets/451510/7357952/12f9f75a-ece7-11e4-88a3-7abe7e8b1110.png)
As well as CoverVirginia's own pre-screening tool:
![covervaprescreener](https://cloud.githubusercontent.com/assets/451510/7357999/7699a4a4-ece7-11e4-9da6-751a0336075b.gif)

**Comment by bengolder** [comment]
Sooo, Medicaid is a bit of a jumble in Virginia. Here is the jumble, via a chart by CoverVA.org:
![screen shot 2015-04-27 at 2 19 14 pm](https://cloud.githubusercontent.com/assets/451510/7358173/a410247a-ece8-11e4-9367-0d6563abf644.png)

**Comment by bengolder** [comment]
![patient_details](https://cloud.githubusercontent.com/assets/451510/7382909/080d369c-edcb-11e4-9941-2e9363f373e8.gif)

**Comment by mapsam** [comment]
I feel like we could create a better graph than that one above ... would it be useful to have that moving forward? Might work better than our simple gap graph.

**Comment by bengolder** [comment]
@svmatthews Yes! I think we should! Particularly because we may want our app to check against it down the road.

**Comment by bengolder** [comment]
Worth noting that the clean team is not adding fields for household income, but only household members.  They instead just rely on documents to show income.

**Comment by esmithayer** [comment]
But they're not doing any kind of quick pre-screening thing, are they?

**Comment by mapsam** [comment]
I was thinking for starters to just make a nice looking graphic for our own usage (i.e. presentations, blog post). At some point we'll have to do FPL calculations, but we can cross that bridge when it comes.

**Comment by bengolder** [comment]
@svmatthews I think we should spin off the FPL chart task as another issue (#40)
@esmithayer no, but for full screening it's worth testing with partners whether details about specific income sources are really needed or if they'd rather just see documents. In Clean's case, the details about income sources were made unnecessary by simply providing documents.

**Comment by mapsam** [comment]
:+1: good call on the separate issue!
