### ISSUE TITLE
Wireframing process

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#160]
I'm trying to find my groove for wireframing, so I'm opening this issue to show you some examples and get your input. I'll close this issue in a week.

**My assumed goal of wireframing is to improve the quality and speed of decision-making about the UI.**

@esmithayer and @mapsam, I assume you two are the main audience at this point. Let me know if the process seems helpful or not for making decisions. I'm open to suggestions & criticisms.

At this point, I'm focusing on the general visual composition of the UI and how it supports or doesn't support the assumed workflows of our users. The illustrations should help us determine which pages are needed, the content for each page, and organization of content for clear hierarchy in the UI.

I'll be illustrating a series of pages, thinking about our assumptions about user actions at each page, and how well the pages support the assumed user needs.

The illustrations will be abstracted and monochromatic, so that we can focus on general visual structure, without addressing the copywriting.

I'll make existing versions and then proposed versions, so we can see where new versions depart from what we currently have.

Here's an example that shows our existing screens for one workflow:
![navigator-referral-prescreen](https://cloud.githubusercontent.com/assets/451510/8343142/25360166-1a87-11e5-9378-af1160b3b501.gif)

**Comment by bengolder** [comment]
I'm also going to make several sizes of each wireframe screen (this is the prescreen results page):
![screen shot 2015-06-24 at 3 43 37 pm](https://cloud.githubusercontent.com/assets/451510/8343213/d6c8e132-1a87-11e5-9d1a-5945f6c70c1e.png)

**Comment by bengolder** [comment]
I just talked with Jazmyn for a while and she showed me some faster wireframing techniques. So I may switch it up.

**Comment by esmithayer** [comment]
Can we close this one @bengolder?

**Comment by bengolder** [comment]
sure

**Comment by mapsam** [comment]
Yup, this is moved over into its own repo now: http://github.com/codeforamerica/rva-screening-ui-prototypes
