### ISSUE TITLE
Add user roles

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#173]
We've talked about four categories of user permissions:
-Patients (can see only their own record)
-Navigators (e.g. OAR) (can see all patients? or just ones they created? or no account at all, just help set up patient accounts?)
-Staff at organizations that screen (can see all patients in network)
-Superusers that can do things like add new organizational user accounts or change service descriptions or fees.

**Comment by mapsam** [comment]
User roles added for: 
- patient
- staff
- admin
- superuser 

but the last three do nothing different currently!
