### ISSUE TITLE
More robust document uploads

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#175]
- [x] Thumbnail versions of images for display on patient details page?
- [ ] Upload progress indicator
- [x] Avoid filename collision

**Comment by mapsam** [comment]
What about including document type as a dropdown (with an "other" option) instead of a text field as well?

**Comment by esmithayer** [comment]
I put that on #168 because it doesn't really involve the file upload code itself :)

**Comment by mapsam** [comment]
Boom.

**Comment by mapsam** [comment]
Closing this for now. We'll save progress indicators for another day!
