### ISSUE TITLE
What views are needed for first version?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#19]
Which screens should we have and how should users navigate between them?

**Preliminary List**
- Nav menu with links to:
  - logout/login
  - pre-screen someone (select a service)
  - add a new client
  - search for an existing client
  - your account details
- Auth views
  - login
  - send me a password reset email
    - we can't find that account
    - it's been sent!
  - email with password reset link
  - the link you used is old or invalid
  - set new password
  - your new password worked!
  - your new password didn't work for some reason
  - logout
- Post login page (should it be pre screen? a menu? your account?)
- Pre Screening views
  - select a service to screen for
  - basic questions for access now and crossover
  - worksheets for difficult questions
    - household worksheet
    - income worksheet
    - do you have insurance worksheet
    - are you eligible for medicaid worksheet
  - you probably are/aren't eligible page
- Client search page
- Client details page (has subsections, could be separate pages)
  - basic info (most needed fields)
  - documents & document upload
  - ID info (SSN, DOB, Name in detail)
  - Contact info (address, phone, email, emergency contact, etc.)
  - FPL (who is in household, income in detail)
  - demographic info (race, ethnicity, gender)
  - insurance / employment info
  - other questions
  - what they have applied for/are eligible for

**Comment by bengolder** [comment]
Diagram of authentication workflow:
![auth_workflow](https://cloud.githubusercontent.com/assets/451510/7261508/2ab2c01c-e827-11e4-897c-cd4622b56ff5.jpg)

Diagram of client search and info:
![client_info_and_docs_](https://cloud.githubusercontent.com/assets/451510/7261509/2ab40670-e827-11e4-9c41-8ff247a18d3e.jpg)

Diagram of screening workflow:
![pre_screening_workflow](https://cloud.githubusercontent.com/assets/451510/7261510/2ab5287a-e827-11e4-8478-d3c0d52b04f3.jpg)

**Comment by mapsam** [comment]
After our talk this morning, here are the main views/templates/routes that we want to prioritize.
- [x] Login/logout
- [x] Landing page: searchable client list with overview stats
- [x] Pre-screen (no patient chosen), choose service **>** fill out questions **>** status & create new patient
- [x] Create new patient (basic info)
- [ ] Patient overview (status, universal questions, expandable pieces, upload documents/images)
- [ ] Patient overview **>** pre-screen (which service > basic questions > status > patient overview)

**Comment by bengolder** [comment]
A diagram based on our meeting this morning
![screen shot 2015-04-22 at 2 26 43 pm](https://cloud.githubusercontent.com/assets/451510/7285719/88ce1f78-e8fb-11e4-9f57-1766e4ae8cff.png)

**Comment by mapsam** [comment]
This looks great!

For the "New Screening" piece, did we decide to not include doing the full screening option since we'll be filling that information out in the _universal_ and _expandable service_ questions? Therefore a "New Screening" would just be choosing a clinic and going from there, without choosing to do the full-screening until a patient record has been created.

**Comment by bengolder** [comment]
I don't think we decided _not_ to do a full screening. We did talk about restricting it to universal questions for the time being. I think of it like we have a big set of questions that we can slice a few different ways. We can separate out:
1. questions common to most or all services (universal Qs)
2. questions unique to a service (expandable service Qs)
3. Big eligibility questions that may be determined by subquestions (pre-screening Qs)
4. all questions asked by a service, a combination of 1 & 2 for a given service, leading to answers for 3 (full screening Qs)

A full screening would be set 4.
A pre-screening would be 3, but may optionally answer subsets of 4.
The Patient Details page lets you view 1 & 2 distinctly.

**Comment by bengolder** [comment]
@svmatthews Is this closer to what you were thinking?
![screen shot 2015-04-22 at 3 06 33 pm](https://cloud.githubusercontent.com/assets/451510/7286488/389526d6-e901-11e4-9747-a74e0e36b9f3.png)

**Comment by bengolder** [comment]
Or this, where the full screening is the Patient Details, and both the patient details and the short pre-screeners link to more detailed worksheets?
![screen shot 2015-04-22 at 3 11 41 pm](https://cloud.githubusercontent.com/assets/451510/7286550/c4462e78-e901-11e4-924c-16cde839bbce.png)

**Comment by mapsam** [comment]
Yah! The second is definitely closer to what I had my head. The third is probably what it would _actually_ be like from a technical perspective. I could also see some of the universal questions being answered in the "New Patient" view as well (though, not required to make a new patient)

Definitely not saying this is the way it needs to be, FTR. Thanks for drawing these up so quickly! :racehorse: :pencil2:

**Comment by bengolder** [comment]
These are good questions. It's important to question the assumed flows, because they rest on big assumptions at this point. It will take questioning and iteration to get us to something simple and good. Between the Patient Details and different ways to do the screening, the big problem is how to organize and stage the questions. More work on the specific questions may help clarify those stages.

**Comment by mapsam** [comment]
Agreed. These flows make it easier to think of possibilities but it seems best to choose a direction, build it, then change it based on user testing.
