### ISSUE TITLE
Pre-screening views

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#20]
This is an issue for discussing the pages and workflows used for pre-screening, a subset of all the views (issue #19).
1. select a service to screen for
2. basic questions for access now and crossover
3. worksheets for difficult questions
   1. household worksheet
   2. income worksheet
   3. do you have insurance worksheet
   4. are you eligible for medicaid worksheet
4. you probably are/aren't eligible page

**Comment by bengolder** [comment]
![pre_screening_workflow](https://cloud.githubusercontent.com/assets/451510/7261697/9b8b83c2-e828-11e4-835a-c4e69c261a35.jpg)

**Comment by bengolder** [comment]
Select a service page:
![img_1513](https://cloud.githubusercontent.com/assets/451510/7262173/71d45d5c-e82c-11e4-9544-e7ae5947b181.JPG)

Basic questions for Access Now
![img_1512](https://cloud.githubusercontent.com/assets/451510/7262178/7ec08568-e82c-11e4-80b3-c2425d62d322.JPG)

**Comment by mapsam** [comment]
![screen shot 2015-04-22 at 9 53 16 am](https://cloud.githubusercontent.com/assets/1943001/7325138/0c86e450-ea71-11e4-8966-d86280580f5a.png)
![screen shot 2015-04-22 at 9 53 08 am](https://cloud.githubusercontent.com/assets/1943001/7325140/0f97f954-ea71-11e4-8af2-d13d5a11c7ff.png)

**Comment by bengolder** [comment]
After the conversation with Daily Planet, we know that anyone is eligible for Daily Planet. The pre-screening Daily Planet page could include just the HH Size & HH Income for calculating FPL, which we can check against their sliding scale fee table.
