### ISSUE TITLE
Browse Clients View

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#21]
This is an issue for discussing the views and workflows around searching for clients and working with their information. It's a sub-issue of #19 (all the views).
1. Client search page
2. Client details page (has subsections, could be separate pages)
   1. basic info (most needed fields)
   2. documents & document upload
   3. ID info (SSN, DOB, Name in detail)
   4. Contact info (address, phone, email, emergency contact, etc.)
   5. FPL (who is in household, income in detail)
   6. demographic info (race, ethnicity, gender)
   7. insurance / employment info
   8. other questions
   9. what they have applied for/are eligible for

**Comment by bengolder** [comment]
![client_info_and_docs_](https://cloud.githubusercontent.com/assets/451510/7261618/14bc15f0-e828-11e4-8206-ccde3f879e36.jpg)

**Comment by bengolder** [comment]
Client Search example:
![img_1509](https://cloud.githubusercontent.com/assets/451510/7262246/e95da220-e82c-11e4-9027-3b564fba45b2.JPG)

Client basic info:
![img_1510](https://cloud.githubusercontent.com/assets/451510/7262258/f9447970-e82c-11e4-8e0c-4855b70c6b98.JPG)

Client identification details:
![img_1511](https://cloud.githubusercontent.com/assets/451510/7262264/0721acc0-e82d-11e4-830f-3c9f7386a624.JPG)

**Comment by bengolder** [comment]
Regarding client search,

Based on shadowing at Access Now, it seems like users would probably search for clients based on name, SSN, and sometimes DOB (particularly if more than one have the same name or don't have SSNs). It might be nice to have a single all-purpose search field that just allows them to type in any name, partial name, phone number, SSN, or DOB and it auto-populates a list that they can choose from.

**Comment by bengolder** [comment]
For the client details, it would make sense to separate out a useful client overview from detail pages that cover all the information used in the forms. So there might be a basic info view that includes Name, phone number, FPL, and docs, but phone numbers, emails, and addresses would all be accessible under the contact information page. This would result in some duplication of fields, which doesn't seem like a problem, as long as they are linked and can update each other.

**Comment by mapsam** [comment]
Two search interfaces that we've talked about:
1. When a user lands on this page they see **all** of the clients and a search narrows down the clients on the page. OR
2. They enter a search, press a button to query the database and return a new "view" with results

I like the former for UI, but the latter seems better with larger databases.

**Comment by bengolder** [comment]
I think we should do 1 for now.

**Comment by bengolder** [comment]
@svmatthews Does this last commit warrant a screenshot?

**Comment by mapsam** [comment]
Nah I think I have a sense of what we want! Updated screencast of the login/patient-overview pages is at #31

**Comment by mapsam** [comment]
I may have misunderstood your last comment - putting the screenshot in this issue to keep things straight!

![rva-patient-overview](https://cloud.githubusercontent.com/assets/1943001/7358548/e0837c02-ecea-11e4-8cb1-5cc47fc22ea3.gif)
