### ISSUE TITLE
Update README with new install instructions

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#22]
We have done a lot since it was last edited.

**Comment by mapsam** [comment]
## Nomenclature

**App** refers to the application being built by the Richmond Fellows.

**User** refers to a screener or individual working in a clinic who would be using the _app_.

**Patient** is a individual trying to access care. This matches the database schema in the _app_ - `class Patient(db.Model)`.

**Service** can be any clinic or other health-related entity in the Richmond area that is using OR may be using the _app_ in the future.

**Application** is an application for a _service_ that a _patient_ would fill out for eligibility and screening purposes.

**Comment by mapsam** [comment]
## Install

... what do you do?

### Update

```
git pull origin master
python app.py db migrate
python run.py
```

**Comment by mapsam** [comment]
Update with new install instructions!

**Comment by bengolder** [comment]
Just tried doing an install with Imanol so he could help with translations

Here's the process (some is already documented) and some noted difficulties
1. clone the repo
2. create a virtualenv and activate it
3. create a database in postgresql (he used PgAdmin3 to do this)
4. make a `.env` file with the database connection string (and in our case, the default language setting as well). I wonder if we can create a new default connection string and database creation command so it "just works".
5. make a separate `.env-export` file that exports the environmental variables and then running `source .env-export`, because just running the scripts on their own doesn't pull in the environmental variables in .env
6. `make install` (I just added this. It just does `python install -r requirements.txt` and `npm install`)
7. `make new_db`
8. `python add_user.py`
9. `python add_mock_data.py` (this didn't seem to add any data, and had no errors. No idea why.)
10. `make run`

One unexplained problem I noticed is that unlike Imanol's new installation, if I edit the `.po` translation files in PoEdit and save (thus overwriting the `.mo` files), then simply reloading a page will show the new translations. On Imanol's computer, he had to stop the running process and restart it to see the changes. Not sure how to solve this, but one option might be to have gulp start the foreman process, watch for file changes, and restart it when relevant files are changed.

Suggestions for easier/faster methods or more ways we could automate this would be :+1:.

**Comment by gideonite** [comment]
I haven't really done more than play around with Docker but I'm curious what people would think about using it to run postgres in a container. This would avoid having to setup a database and potentially configure a `.env` file.
