### ISSUE TITLE
update many-to-one field deletions that don't have state set as Virginia

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#223]
Taken from #183

**Comment by mapsam** [comment]
[Here is the specific line of code!](https://github.com/codeforamerica/rva-screening/blob/master/app/views.py#L139)

**Comment by mapsam** [comment]
More generally, we should give all dropdowns a null value so they delete (bug exists in the employers section as well)

**Comment by esmithayer** [comment]
We probably don't want people saving address entries that are just a state and nothing else, or just a patient/spouse selection in the employer section and nothing else. I coded it so that a row that's empty except for one of those dropdowns is considered empty and is deleted.

**Comment by mapsam** [comment]
Good call!
