### ISSUE TITLE
adding a new many-to-one field copies validation classes as well

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#228]
Right now if you have an invalid input on a many-to-one form and click to add a new one, the validation class copies as well. Since we are clearing all input values, we should also clear up any validation classes.

**Comment by bsmithgall** [comment]
@mapsam I wrote a somewhat [generalized jQuery plugin](https://github.com/codeforamerica/pittsburgh-purchasing-suite/blob/master/purchasing/static/js/shared/multipartForm.js) to do the copying. It might be helpful to you.

**Comment by mapsam** [comment]
Thanks for the snippet, @bsmithgall!

This is no longer an issue since we are now using a hidden "clone" for adding new fields, and not copying pre-existing inputs.
