### ISSUE TITLE
Login / forgot password view

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#23]
I'm working on the login flow for a user, including what they would see if they forget their password. Below is a screencap of the potential workflow. _Note: there would be an email in the middle of it for password reset_.

![rva-screener-loginflow2](https://cloud.githubusercontent.com/assets/1943001/7262897/15e1c59c-e832-11e4-887e-c4727c639327.gif)

**Comment by mapsam** [comment]
@bengolder I know we talked about getting rid of the need for logging in again once you've reset your password. I can include that in the next version once we establish a landing page after a successful login.

**Comment by bengolder** [comment]
awesome! looks great!

**Comment by migurski** [comment]
Consider using Mozilla Person for this, so you don’t need to build it? 
- https://login.persona.org/about
- http://www.codeforamerica.org/blog/2013/11/21/securing-the-louisville-app/

**Comment by bengolder** [comment]
Hmm, sounds compelling. Before I thought it was browser specific, but it looks like it's mainly implemented as an API, with portions that would be accessed through Javascript or on the backend. I also like Team Louisville's spreadsheet for different auth roles.

**Comment by mapsam** [comment]
@migurski do you know if Persona can be integrated into the page or does it require the popup? This app has to be mobile-friendly and popups start to ruin that experience.

I think @bsmithgall has been using this as well?

**Comment by migurski** [comment]
It does require the pop-up; I believe the pop-ups work reasonably well on mobile. Maybe try logging into http://engine-light.codeforamerica.org which uses it?

I’ve stubbed out a how-to guide: https://github.com/codeforamerica/howto/blob/06ac1d0399df704a54e07dc6a40a2d11518d9633/BrowserID.md

**Comment by migurski** [comment]
(just tried on iOS, works fine)

**Comment by mapsam** [comment]
"but you should have a great reason not to"

Thanks, @migurski!

**Comment by bsmithgall** [comment]
@svmatthews here's the only decent anti-persona thing I could find (from 2012), would be curious what @migurski thinks about it: http://opine.me/mozilla-persona-browserid-is-a-step-in-the-wrong-direction/

**Comment by migurski** [comment]
Reading the thing, thanks! They seem to be a little confused about the role Persona plays in the login process. The idea that your session is still valid with Persona is analogous to the way you stay logged-in to Facebook or Twitter if you use those services as 3rd-party auth. The other criticisms are definitely valid.

My feeling is that Persona remains the least-bad option for fellowship app logins, and the amount of time & energy recovered from developing login flows, remembering to salt passwords, and connecting to email providers for password resets is worth the cost. There’s so much to get wrong with security. Persona is an adequate-enough approach for alpha-level applications.

**Comment by migurski** [comment]
Wrote more; would love input/comments/feedback before I merge this: https://github.com/codeforamerica/howto/blob/8184a5f/BrowserID.md

**Comment by bsmithgall** [comment]
Left a few comments, otherwise :+1: LGTM

**Comment by migurski** [comment]
Diddly-done: https://github.com/codeforamerica/howto/blob/master/Persona.md

**Comment by bsmithgall** [comment]
@migurski also curious what your opinions are around some of these sso-as-a-service type things (https://stormpath.com/, for example)
