### ISSUE TITLE
after autologout, if you wait another 15 minutes things break

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#264]
When the autologout occurs and you don't touch the computer for another 15 minutes (happens to me a lot) you get a trace error saying "user has no email", which I believe is due to losing the session information. We might want to put a setting on the javascript autologout that only runs if a user is logged in already.

**Comment by esmithayer** [comment]
Fixed in the branch I'm working on--usually happens when you make changes and your local server restarts.

**Comment by mapsam** [comment]
Ah, nice. Thanks!
