### ISSUE TITLE
Getting encoding error on login

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#32]
When I try to log in I get this error:

```
TypeError: Unicode-objects must be encoded before hashing
```

Creating a new user doesn't do it, either. I probably botched something!

**Comment by bengolder** [comment]
Is this resolved or can it be recreated?

**Comment by mapsam** [comment]
Not resolved, still can't log in. Will show tomorrow.

**Comment by mapsam** [comment]
@esmithayer helped debug this one by adding `.encode('utf8')` to the password hash in `views.py`. Will create a PR with this fix.
