### ISSUE TITLE
Patient Details Page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#36]
This issue is for discussing the layout and design of the Patient Details page, which at this point is roughly equivalent to a Universal Eligibility Form. This is one of the more complicated pages, and may need to be broken out into subsections. Some of the topics it should cover is:
- Basic Info
- Documents
- Household Size
- Household Income
- Contact Info
- Demographic Info
- Employment Info

**Comment by bengolder** [comment]
An in-progress snapshot, using tables for documents, household size, and income sources:
![patient_details](https://cloud.githubusercontent.com/assets/451510/7382936/92b615a2-edcb-11e4-91e4-37fd57ff720e.gif)

**Comment by mapsam** [comment]
Nice! This looks great. 

Just to clarify, are the first fields editable when the user clicks on them? And essentially if they make changes they can press the "save patient info"?

**Comment by bengolder** [comment]
With this page, I'm leaning towards a pattern of having readable information and then clicking through to worksheets for editing. So I think the "Basic Info" would be just static information, but you could click over to worksheets for contact and identity info. I'm about to add more content, such as employment and demographic information as well.

**Comment by mapsam** [comment]
Sounds good - keep on rolling :roller_coaster:

**Comment by mapsam** [comment]
@bengolder here are some helper classes from the CSS that might be useful in showing percentages like this image

![screen shot 2015-04-29 at 11 28 59 am](https://cloud.githubusercontent.com/assets/1943001/7398295/02120ec8-ee63-11e4-95b1-348bd4517b4a.png)

``` CSS
.completion {
   color:#FF851B;
   font-weight:900;
   font-size:1.1em;
   float:right;
 }
 .completion.high {
   color:#3D9970;
 }
 .completion.med {
   color:#2ECC40;
 }
 .completion.low {
   color:#FF4136;
 }
```

And the HTML from the above:

``` HTML
<p><strong>Universal</strong> <span class="completion med">75%</span></p>
<p>- Access Now <span class="completion">84%</span></p>
<p>- Daily Planet <span class="completion">56%</span></p>
```

It's important to note that whatever constitutes "high", "medium", and "low" is completely arbitrary right now.

**Comment by bengolder** [comment]
Another in progress snapshot:
![patient_details](https://cloud.githubusercontent.com/assets/451510/7402433/94b7a856-ee80-11e4-846c-282162a44457.gif)

**Comment by bengolder** [comment]
Some observations about forms from the Clean Team (also relevant to #19 generally):
- 48px is a convention for tappable targets on mobile (ours are smaller)
- They try to stick to only about 3 fields for page
- They use pagination through the form, storing info with the session on the backend
- They use significantly more copy and explanations, using plain language, iterating on this a lot
- Validation led to more pagination, because some needs to happen on the backend.
- How little can be done? The testing will bring up tons of issues, so how many things are unnecessary?

**Comment by andreasRVA** [comment]
These look like great! Exactly what I was imagining. Will it be photo uploads of the documents in the app?

**Comment by esmithayer** [comment]
Yup that's the plan!

**Comment by bengolder** [comment]
I've been wondering about how the name field (first?, last?, full legal?) should be structured, and I came across this great guide by W3C:
[How do people's names differ around the world, and what are the implications of those differences on the design of forms, databases, ontologies, etc. for the Web?](http://www.w3.org/International/questions/qa-personal-names)

**Comment by mapsam** [comment]
Task for May visit
- [x] explicit referral buttons, have different orgs, and confirmation
- [x] no permission view with consent button
- [x] expandable sections
- [x] show document recent edits/date
- [ ] save as pdf link

**Comment by mapsam** [comment]
@bengolder what do you think of this tabulated nav for patient-related pages?

![rva-screener-edithistory](https://cloud.githubusercontent.com/assets/1943001/7659852/f8be1846-faf9-11e4-9139-12f5ff1a5fd9.gif)

**Comment by esmithayer** [comment]
What if we put the prescreening in a tab too?

**Comment by mapsam** [comment]
Definitely possible - I just wasn't sure how that would work on the prescreening route. Would we show the tabs there as well?

**Comment by bengolder** [comment]
@svmatthews the tabs aren't working for me on mobile: 
![screen shot 2015-05-15 at 4 25 50 pm](https://cloud.githubusercontent.com/assets/451510/7663438/4404c69a-fb1f-11e4-9208-6fe21e280103.png)

**Comment by mapsam** [comment]
Good catch! I'll take a look in a bit here.

**Comment by bengolder** [comment]
I'd like to close this issue and open anything specific that is arising on this page.

**Comment by mapsam** [comment]
:+1:
