### ISSUE TITLE
An idea: Copy to clipboard buttons on tons of the form fields

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#38]
A lot of our users will need to transfer information from our fields to their own databases. It might add a lot of convenience for them if they could simply click a button to copy the value of the field into their clipboard for pasting into their own database system.

example:
![screen shot 2015-04-29 at 11 09 51 am](https://cloud.githubusercontent.com/assets/451510/7397906/4b3bfc4c-ee60-11e4-8cea-19bdc9ee6586.png)

**Comment by bengolder** [comment]
[Requires Flash](http://stackoverflow.com/a/3953655/4508635) :( 
[More details](http://stackoverflow.com/questions/127040/copy-put-text-on-the-clipboard-with-firefox-safari-and-chrome)

Might still be a useful thing on Desktop browsers that support flash. Here are two libraries:
- [Clippy](https://github.com/mojombo/clippy)
- [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard)

**Comment by bengolder** [comment]
Interesting new development: http://output.jsbin.com/nivuho/quiet

**Comment by mapsam** [comment]
Nice!

**Comment by mapsam** [comment]
Looks like MDN is writing about this as well - might be worth implementing the non-flash version to see what it's like. https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent

I think at the very least, we might want to select the entire field when a user clicks on a text field, so they don't have to triple click to copy everything themselves.
