### ISSUE TITLE
Printable Patient Overview

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#39]
I'm recalling that Danny specifically asked if the app would allow you to print out a patient's details, so it might be nice to have a well-formatted read-only view for printing in the MVP, if time permits.

**Comment by mapsam** [comment]
Bare-bones print route set up!

![rva-screener-printroute](https://cloud.githubusercontent.com/assets/1943001/7656950/e227c526-fae2-11e4-8c91-24bd93d6dab7.gif)

**Comment by mapsam** [comment]
Going to add more information to the print page.

**Comment by mapsam** [comment]
Huzzah!

**Comment by mapsam** [comment]
![screen shot 2015-05-15 at 5 50 53 pm](https://cloud.githubusercontent.com/assets/1943001/7664007/026f180a-fb2b-11e4-85bd-52be8a2e0377.png)
