### ISSUE TITLE
Make a chart of FPL & program eligibility

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#40]
A lot of programs have basic eligibility requirements based on FPL. For example, Access Now only accepts patients who are under 200% FPL and are not eligible for Medicaid or other insurance. 

It would be useful to have a chart, or at least a chartable spreadsheet, that documents these different FPL eligibility windows in detail. We could use this info for pre-screening checks, if we have a patient's FPL.

Here is a chart from CoverVA.org as an example:
![screen shot 2015-04-27 at 2 19 14 pm](https://cloud.githubusercontent.com/assets/451510/7358173/a410247a-ece8-11e4-9367-0d6563abf644.png)

**Comment by mapsam** [comment]
Versions we've used:

![screen shot 2015-04-30 at 5 48 26 pm](https://cloud.githubusercontent.com/assets/1943001/7425186/286d6988-ef61-11e4-92b8-4d55687221c5.png)

![screen shot 2015-04-30 at 5 48 31 pm](https://cloud.githubusercontent.com/assets/1943001/7425187/2b7280fa-ef61-11e4-90ad-a6c873f86487.png)

**Comment by bengolder** [comment]
A good version of this graphic would be great for our April blog post, to illustrate the toughness of screening.

**Comment by mapsam** [comment]
Exactly what I was thinking! I'll post some examples in here as I go

**Comment by mapsam** [comment]
Here's an updated version - no information change, just cleaner. 

![screen shot 2015-04-30 at 7 53 39 pm](https://cloud.githubusercontent.com/assets/1943001/7426206/dca211f2-ef74-11e4-9116-b1eb18941d4d.png)

**Comment by esmithayer** [comment]
That's pretty! Can we make a version without Plan First? It's so limited it seems misleading to include it. It's probably worth including GAP, though. We should probably also distinguish between subsidized marketplace plans and non-subsidized (which people are unlikely to actually be able to buy). The CoverVA version just makes it look like there's no insurance gap.

**Comment by alanjosephwilliams** [comment]
dig the style. what is FAMIS (if only we had glossbot for github issues)?

On Fri, May 1, 2015 at 9:40 AM, esmithayer notifications@github.com wrote:

> That's pretty! Can we make a version without Plan First? It's so limited
> it seems misleading to include it. It's probably worth including GAP,
> though. We should probably also distinguish between subsidized marketplace
> plans and non-subsidized (which people are unlikely to actually be able to
> buy). The CoverVA version just makes it look like there's no insurance gap.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/rva-screening/issues/40#issuecomment-98174614
> .

## 

t:  @alanjosephwilli
p: 817 713 6264

**Comment by bengolder** [comment]
"FAMIS is Virginia's health insurance program for children" via http://www.coverva.org/programs_famis.cfm

**Comment by mapsam** [comment]
I agree, @esmithayer - I'll get something put together right away and keep posting changes. Planning on having something so we can use in the upcoming blog post.

**Comment by mapsam** [comment]
Is the extra bit of Medicaid for parents and caretakers based on the Median FPL of 44%? I want to make sure that I get the number set properly! 

44% coming from this article: http://kff.org/health-reform/issue-brief/the-coverage-gap-uninsured-poor-adults-in-states-that-do-not-expand-medicaid-an-update/

**Comment by bengolder** [comment]
@svmatthews I think you should email a draft of your chart and your understanding of the FPL levels to our VPLC contacts to get their input. They are probably our best resources for this, especially since we started with their chart.

**Comment by mapsam** [comment]
Here's the chart without Plan First and adding GAP.  I'm a little uncertain where the unsubsidized and subsidized break is for adults, @esmithayer ... Is it the 138% to 200%? 

![screen shot 2015-05-04 at 10 56 11 am](https://cloud.githubusercontent.com/assets/1943001/7458807/346dce92-f24c-11e4-8de4-22825dcd8009.png)

**Comment by mapsam** [comment]
Good idea, @bengolder. Does the above image seem okay enough to send for questions? If there are some obvious inconsistencies I'll fix those up before sending to them.

Some questions I have:
- What are the specifics of the < 30% for "Parents & Caretaker Relatives"
- Where do subsidized marketplace plans and unsubsidized marketplace plans intersect?
- Is it worth showing above 200%? (i.e. 200 - 400%) or should we cut that piece shorter since it doesn't specifically relate to VA?

**Comment by esmithayer** [comment]
I think the 44% is a median of a bunch of states. Looks like 49% in VA here: http://www.medicaid.gov/Medicaid-CHIP-Program-Information/By-State/virginia.html
But that doesn't match Cover VA's chart, so it's probably worth confirming. Cover VA isn't affiliated with VPLC (that's Enroll VA)--but I'm sure they'd be a great resource regardless.

I think the marketplace subsidies are 138-400% FPL, and I think it's worth showing up to 400% in the graph since that's the range of people getting some government help.

**Comment by esmithayer** [comment]
Other sources say marketplace subsidies start at 100% FPL, though. Not sure what's up with the discrepancy.

**Comment by mapsam** [comment]
That medicaid.gov link definitely clarifies some of this - thanks for sending that along!

The CoverVA chart shows that 100% but it gets twisted with Plan First. It's actually pretty confusing that the CoverVA chart has nothing related to the 138% break, which is the big number right now in VA for those not covered by a lack of Medicaid expansion. http://www.vplc.org/in-session-close-the-medicaid-coverage-gap-for-up-to-400000-low-income-virginians/

**Comment by bengolder** [comment]
@svmatthews :thumbsup: on being ok to share. You may also just want to call them on the phone to get a quicker answer.

Regarding:

> Where do subsidized marketplace plans and unsubsidized marketplace plans intersect?

I think the subsidy is in the form of a tax credit with income taxes are filed. I'm don't think it's so much on a subsidy for the plan (I think it includes any plan in the exchange), but rather a subsidy for the person buying the plan when they file for taxes. [More details](http://kff.org/health-reform/issue-brief/the-coverage-gap-uninsured-poor-adults-in-states-that-do-not-expand-medicaid-an-update/).

I agree that showing up to 400% is useful.

**Comment by esmithayer** [comment]
I think there are both direct subsidies and tax credits, depending on your income: http://obamacarefacts.com/obamacare-subsidies/

But not sure if that's an important distinction to show in the chart.

**Comment by mapsam** [comment]
Considering closed with new blog post rva.codeforamerica.org/april
