### ISSUE TITLE
Merge front-end prototyping into Flask & Jinja

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#42]
Now that the back end has the routes fleshed out, I think we should start prototyping on the front end with Flask & Jinja instead of Jekyll. This way, we don't build up a technical debt of making templates that won't work with Jinja or Flask.

There are some decisions to make, though.
1. Should we move front-end prototyping to a branch off master that doesn't use Jekyll?
2. Currently Jekyll [allows us to fake data using YAML front matter](https://github.com/codeforamerica/rva-screening/blob/template-prototypes/patient_existing.html#L1-L57), how should we fake data in Flask/Jinja for front-end prototyping in a way that does not interfere with back-end logic?

**Comment by bengolder** [comment]
Here's the current route to template arrangement:

| **converted?** | **route** | **template** |
| --- | --- | --- |
| yes | `/login/` | `login.html` or `<redirects to index.html>` |
| yes | `/logout/` | `<redirects to index.html>` |
| yes | `/new_patient/` | `patient_details.html` |
| yes | `/patient_details/<id>/` | `patient_details.html` |
| yes | `/delete/<id>/` | `<redirects to index.html>` |
| no | `/document_image/<image_id>/` | `documentimage.html` |
| no | `/documentimages/<filename>/` | `<sends image from directory>` |
| yes | `/new_prescreening/<patient_id>/` | `new_prescreening.html` |
| yes | `/new_prescreening/` | `new_prescreening.html` |
| yes | `/prescreening_basic/` | `prescreening_basic.html` |
| yes | `/prescreening_results/` | `prescreening_results.html` |
| yes | `/save_prescreening_updates/` | `<redirects to patient_details.html>` |

**Comment by bengolder** [comment]
I'm working on merging, and I'll document the process and decisions here for your feedback & criticism.

I'm trying to keep the content of the jekyll templates while converting the logic to flask & jinja. So they should look the same when I'm done.

Where Jekyll fed in context data to the templates, I'm adding dictionaries to the views in flask and passing them into the template context as `page`. This allows for us to see which data is being fed into each view, and then move that data elsewhere for prototyping until there is a better match for serialized data being passed between front-end and back-end. Here is an example:

``` python
@app.route('/' )
@login_required
def index():
  session.clear()
  patients = Patient.query.all()
  # context for template
  page = {
          "login": True,
          }
  return render_template('index.html', patients=patients, page=page)
```

**Comment by mapsam** [comment]
Seems good to me! 

FWIW: that specific `login` parameter already has that logic built in with `@login_required` specified after the route declarations.

**Comment by bengolder** [comment]
Yes! I'm going to substitute wherever I can with appropriate Jinja and Flask stuff. After digging around, it's now:

in `app/views.py`:

``` python
@app.route('/' )
@login_required
def index():
  session.clear()
  patients = Patient.query.all()
  return render_template('index.html', patients=patients)
```

in `app/templates/includes/nav.html`:

``` html+jinja
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url_for('new_prescreening') }}"><span class="glyphicon glyphicon-pencil push-right" aria-hidden="true"></span>Pre-Screener</a></li>
        {% if g.user.is_authenticated() %}
        <li><a href="{{ url_for('index') }}"><span class="glyphicon glyphicon-search push-right" aria-hidden="true"></span>Browse Patients</a></li>
        <li><a href="{{ url_for('new_patient') }}"><span class="glyphicon glyphicon-plus push-right" aria-hidden="true"></span>Add Patient</a></li>
        <li><a href="{{ url_for('logout') }}"><span class="glyphicon glyphicon-log-out push-right" aria-hidden="true"></span>Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('login') }}"><span class="glyphicon glyphicon-log-in push-right" aria-hidden="true"></span>Login</a></li>
        {% endif %}
```

But as a temporary solution for any data I'm not sure how to deal with, I'll just put it in the `page` dictionary for the view, as shown above.

**Comment by mapsam** [comment]
Nice! Keep rolling with the :book: stuff. I like that.

**Comment by bengolder** [comment]
Just pulled out the example data in a slightly different way than I had said before, because I ran into an error.

Here is what it looks like in the view:

``` python
# example data for front-end prototyping
from app import example_data

@app.route('/prescreening_results')
@login_required
def prescreening_results():
  if 'services' in session:
    services = session['services']
  else:
    # example data
    services = example_data.services
  if 'patient_id' in session and session['patient_id']:
    return render_template(
      'prescreening_results.html',
      services = services,
      patientid = session['patient_id']
    )
  else:
    return render_template('prescreening_results.html', services = services)
```

Check out [`app/example_data.py`](https://github.com/codeforamerica/rva-screening/blob/merge_templates/app/example_data.py).

**Comment by mapsam** [comment]
I like how `example_data.py` is it's own file. Will accessing the database columns be similar in syntax?

**Comment by bengolder** [comment]
I don't mean to imply anything about the database structure at this point. For now it is just a rough sketch of data so that we can test different ideas in the templates.

In Jinja templates, you can access object attributes or dictionary keys in the same manner. Is that what you are asking?

``` html+jinja
{{ thing.key }}
```

**Comment by mapsam** [comment]
Right, I understand the Jinja stuff. Was just curious if there was any shared system that I wasn't aware of between keys in the dictionary and what we expect in the database, but there isn't.

**Comment by bengolder** [comment]
The Jekyll templates have been shifted over to Flask templates. The `merge_templates` branch should still probably stay separate from `master` until the forms are aligned with the backend views.

**Comment by mapsam** [comment]
Huzzah! `jekyll` is but a distant memory of a time long ago. Can this be closed?

**Comment by bengolder** [comment]
It is closed already.

**Comment by mapsam** [comment]
Whoa, weird. I commented on this one from waffle and it wasn't showing as complete.
