### ISSUE TITLE
How should documents be uploaded at a clinic?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#5]
Would they have a scanner on hand? Would it be a pain to transfer images from the scanner to the web app?

Could a screener take pictures with their phone? If so, what would be the easiest way to transfer those images to the app? Should they log in on their phone? Would they rather just use a USB?

Would they want to be able to fax documents to a phone number in order to load them? How would we link the docs to the correct account?

**Comment by mapsam** [comment]
This seems like a question that would be best answered by the screeners themselves. It sounds like a hassle to log into the application twice, once on desktop and once on phone, but that seems like the best way to handle the actual upload properly without requiring the screener to move files across devices.

For all we know right now, they might already have a document scanning process set up at some clinics, which we could tap into.

**Comment by bengolder** [comment]
Currently, Daily Planet has a scanner within arm's reach of front desk staff that is directly connected to the computer. I don't think this is an issue we need to address ourselves apart from simply providing fields that allow for file uploads which work on both mobile and desktop.
