### ISSUE TITLE
OperationalError "Incorrect integer value" on /save_prescreening_updates

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#50]
When clicking the "return to patient details" link in the `/prescreening_results` view, I get this error on this URL `http://localhost:5000/save_prescreening_updates?patientid=1`:

```
OperationalError: (OperationalError) (1366, "Incorrect integer value: 'None' for column 'householdsize' at row 1") 'UPDATE patient SET householdsize=%s, householdincome=%s WHERE patient.id = %s' (u'None', u'None', 1L)
```

![screen shot 2015-05-05 at 12 13 00 pm](https://cloud.githubusercontent.com/assets/1943001/7480824/33fc8398-f320-11e4-9f07-436a3f7efff0.png)

Let me know if you'd like the full traceback!

**Comment by bengolder** [comment]
This is because there was fake patient data fed to the prescreening results page, so no patient information was being stored in the session (and thus couldn't be used to access the patient's detail page).

**Comment by mapsam** [comment]
Sounds good, thanks for clarifying @bengolder! I'm going to close this since it seems less of a "bug" and more of a result of not populating/working with the database yet.
