### ISSUE TITLE
Make a form field dependency chart

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#51]
We need a visual representation of the dependencies between questions, in order to more easily understand the implied logic in the eligibility screening forms, and to better coordinate between back end and front end

**Comment by bengolder** [comment]
I wanted to make a chart that could be easily shared, and which we could use internally as well as for having conversations with clinics. So I'm implementing this as [a spreadsheet + tabletop.js static webpage](http://bl.ocks.org/bengolder/raw/756fc2c5de5d8c238247/). It kind of sucks at the moment, but I have a few ideas to make it nicer. I plan to incorporate ways redraw the layout to show:
- just the dependency tree of fields that depend on each other
- questions based on the providers that use them
- the sets of options for multiple selection fields
- screenshots of fields that have been implemented, where available
- screenshots of the fields in the actual paper form, for a given clinic, where available.

**Comment by mapsam** [comment]
Yay tabletop! Great idea. Making this visual will be really helpful for me :eyes:

**Comment by bengolder** [comment]
One other slightly tricky thing is deciding how to represent form sections that are essentially subtables. 

For example, a list of household members. Each household member has a series of fields. 

If the person lives alone, then tons of questions can be skipped and we don't need any household members. If they have a spouse, we want to make sure that the spouse is listed. 

Total household size, an important field, should probably be _calculated_ from the household member list.

So some fields are dependent on other in the sense that they should be displayed based on the parent question's answer, while other questions are dependent in the sense that they have values that are calculated from other questions or tables. **dependent value** and **dependent display** are two types of dependency.

**Comment by bengolder** [comment]
Updated to show questions whose display should probably depend on answers to other questions
![dependency_chart](https://cloud.githubusercontent.com/assets/451510/7577217/d76dc418-f7fa-11e4-8deb-06c5bb3a4a44.gif)
