### ISSUE TITLE
Patient search functionality

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#56]
- [x] user can search their patients
- [x] user can search for new patients (and see where they are from)

**Comment by mapsam** [comment]
Here are some screenshots of the search functionality:

**Search your patients**
![rva-screener-searchyourpatients](https://cloud.githubusercontent.com/assets/1943001/7638295/97520896-fa28-11e4-8391-f5f0f455d3eb.gif)

**Search new patients & request**
![rva-screener-newsearch](https://cloud.githubusercontent.com/assets/1943001/7638298/9d277b48-fa28-11e4-846b-3d8ffc388e3b.gif)

**Comment by mapsam** [comment]
Marking this as resolved!
