### ISSUE TITLE
Update landing page to sort by most recent action, highlight patients who were sent to you

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#57]

**Comment by mapsam** [comment]
Do we want to do this in the DB or just come up with a hard coded version for now?

**Comment by bengolder** [comment]
hard-coded now, DB later

**Comment by mapsam** [comment]
- [x] recent patients
- [x] show new patients
- [x] show patient % progress

**Comment by mapsam** [comment]
Not going to add the functionality for filtering yet, but here is a shot from #84 

![screen shot 2015-05-17 at 7 50 52 pm](https://cloud.githubusercontent.com/assets/1943001/7672800/2e61b4a0-fcce-11e4-8037-d8626efa13be.png)
