### ISSUE TITLE
Make audit history mockup

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#59]

**Comment by mapsam** [comment]
![screen shot 2015-05-15 at 10 00 52 am](https://cloud.githubusercontent.com/assets/1943001/7657758/54d66c84-fae9-11e4-99d7-186a593fb407.png)

**Comment by mapsam** [comment]
I'd like to ask what our users would like to see on this page. How much information is necessary?

**Comment by mapsam** [comment]
Edit history is now part of the patient navigation!

![rva-screener-edithistory](https://cloud.githubusercontent.com/assets/1943001/7659337/1a43db6c-faf6-11e4-9602-fa268f93c708.gif)
