### ISSUE TITLE
make css work on mobile

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#62]
Recent changes have left the layout broken. We should go back over the layout and make repairs once the fields are finalized.

**Comment by bengolder** [comment]
![layout](https://cloud.githubusercontent.com/assets/451510/7615913/88c23e1e-f955-11e4-9599-c2ef69245f27.gif)

**Comment by mapsam** [comment]
Current sections having the issue:
- [ ] Employment Information
- [ ] Personal documents
- [ ] Household

**Comment by mapsam** [comment]
Here's a quick option to handle table `overflow-y` - probably not the best UI, but better than broken!

![rva-screener-overflowy](https://cloud.githubusercontent.com/assets/1943001/7641589/9ee204f0-fa3f-11e4-8872-03d69fdd1355.gif)

**Comment by mapsam** [comment]
@bengolder @esmithayer put any mobile issues you see in this issue!

**Comment by esmithayer** [comment]
Closing #85 so this issue can cover all mobile bugs.
