### ISSUE TITLE
Pathway: Second Clinic - Existing Account

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#7]
This story examines the process when a client with an existing account goes to a second clinic. The screener at the second clinic can review the client's eligibility as verified by previous clinics.

To validate the app, this process should be much easier than the current screening process.

https://docs.google.com/a/codeforamerica.org/presentation/d/1kVSFagS9laHCniL0LRNoi-thlp67J9w3oiGaUlbYAsQ/edit?usp=sharing

**Comment by mapsam** [comment]
I see this related to #6 and #9. It seems a service will ask the client if they are part of this program, if they are they can check the client's information, otherwise they can get signed up.

**Comment by bengolder** [comment]
for context, this would be likely to happen at Daily Planet, Crossover, Bon Secours, or Access Now.

**Comment by bengolder** [comment]
The screening for the 2nd clinic may already have been done by the first clinic. For example OAR or Resouce Center staff might help someone fill out an application for Crossover, Daily Planet or VCU. There are two types of referrals regarding the app:
1. formal referral (staff at clinic A tells staff at clinic B that they're sending someone over)
2. informal referral (staff at clinic A mentions clinic B, patient goes to or calls clinic B on their own)

Furthermore, the fraction of the screening application and doc uploads completed would be unknown. The only real expectation is that there is enough info to ID a patient in the app.
