### ISSUE TITLE
settle on a name for the app

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#73]
Or "Thomas Jefferson Screening Machine"

**Comment by mapsam** [comment]
"screen :facepunch:"

**Comment by bengolder** [comment]
Here's some recent ideas:
- Checkbox
- Loop
- Relay
- Patch
- Mend
- Stitch
- Check

**Comment by mapsam** [comment]
#### Overlap

This came out in meeting with Danny and Andreas when Danny used the word "crossover" to describe the differences/similarities in form questions. He then corrected himself to ... "overlap" ... which I thought would be a sweet name for this application.

**Comment by bengolder** [comment]
CareCheck
CareCheckbox
CarePass
CarePatch
ChaCha - (from Community Health Advocate)
ChaChaPass
CareKey

**Comment by mapsam** [comment]
:+1: CareCheck

**Comment by mapsam** [comment]
`care.ch/eck`

**Comment by mapsam** [comment]
Porch - @michaelkolbeVA likes this :wink: 
Screen Porch
Rocking Chair
KeyVA
Portkey

**Comment by michaelkolbeVA** [comment]
Feedback:
Porch -- I like it, but my hesitation is that it's pretty vague. 
Checkbox -- I also like it, especially how it makes it sound easy to "jump through the hoops"  
Overlap -- I like that too.  Made me think of similar words along the lines of connection/collaboration/working together and the end result was this:

RVA HealthLink
HealthLink

**Comment by esmithayer** [comment]
Portkey like http://harrypotter.wikia.com/wiki/Portkey :grinning:?

**Comment by mapsam** [comment]
![portkey](https://cloud.githubusercontent.com/assets/1943001/9362704/1cc3e2d6-4670-11e5-8b79-c825ff7c45d9.gif)

**Comment by michaelkolbeVA** [comment]
let's just call it what we've all really wanted for so long but were afraid to suggest:

THE DEMENTOR SLAYER

**Comment by mapsam** [comment]
"Not Azkaban"

**Comment by mapsam** [comment]
After a mostly negative response on JetScreen and ZipScreen, we are still in a place without a confirmed name. The general consensus of feedback was to make it something that is specifically related to what the application does, and something that is specifically related to RVA.

After considering this feedback, I'm of the opinion that something more descriptive is better than something more vague (whether I _want_ that or not, it seems best for the ownership of the application in RVA).

Some of the resulting names are as follows:

EligibleRVA
RVA HealthLink
Richmond Health Screener
RVA Screener (current name)
RVA Eligibility Screener

**Comment by mapsam** [comment]
Shikita wants it to be called "Referral Buddy" which is adorable and awesome
