### ISSUE TITLE
Pathway: Client updates or adds a document

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#8]
This story examines how a client could add or update a missing or outdated document on their own.

Some major questions about this:
- How should the client login to access their account?
- Should this be implemented as a mobile web app?
- How is the client onboarded from an assisted account creation to knowing that they need another document and uploading it?
- Will this be a reliable way to get images of documents or will the quality of photos be too sporadic?

https://docs.google.com/a/codeforamerica.org/presentation/d/18e3O9_jScA95VQmNUT6jOMkJiGRaVGlQ1Yyctu8K2Cc/edit?usp=sharing

**Comment by mapsam** [comment]
It seems useful to show what prompts the user to take this action. @esmithayer points out that showing a text to the user saying they need to update their documents would be helpful.

Accessing via a web application seems like the best place to start. Uploading their documents in another way seems like it could be quite difficult without a phone camera. I'd be interested to see a fork here saying "do you have a mobile camera?" if **yes** please upload on our site, if **no** please bring your documents to your next appointment so they can be uploaded for you to use.

**Comment by bengolder** [comment]
There is no patient facing app for the time being.
