### ISSUE TITLE
Set up "tooltips" on hover for more explanation

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#83]
Some questions and other UI elements may require some extra explanation without adding more text to the page. Let's find a simple tooltip library to help with this!

Here are a couple:
- [Tooltipser (jQuery)](http://iamceege.github.io/tooltipster/)
- [CSS Only example (yay!)](http://cbracco.me/a-simple-css-tooltip/)

**Comment by mapsam** [comment]
- [HubSpot/tooltip](https://github.com/HubSpot/tooltip)
- Github uses [Tipsy](https://github.com/jaz303/tipsy)

**Comment by mapsam** [comment]
Tried out tipsy, this is what's happening:

![tipsy-error](https://cloud.githubusercontent.com/assets/1943001/7823998/24ff868c-03c5-11e5-9bdd-df2d2ee98648.gif)

**Comment by mapsam** [comment]
Working to Tooltipser and it seems really great. There's a lot of customizing we can do (especially with colors and text size). 

![rva-screener-tooltips1](https://cloud.githubusercontent.com/assets/1943001/7824350/e8a47b86-03c7-11e5-9b0b-774e49d29870.gif)

**Comment by bengolder** [comment]
tipsy looks like it went crazy.

**Comment by mapsam** [comment]
It completely broke down, sadly. Tooltipster seems to be working great, though!

Adding a tooltip is pretty slick - here's an example with an info icon using the `.tip` class (from address gif above):

``` HTML
<span class="glyphicon glyphicon-info-sign tip" title="this is information about the address" aria-hidden="true"></span>
```

There are a bunch of options we can pass, including `position` but just keeping it at the defaults for now seems okay.

**Comment by bengolder** [comment]
How does this work if someone is on a mobile phone?

**Comment by mapsam** [comment]
Right now since it is hover-based, it likely doesn't. We could update to be on click if user is on mobile? The usage of tooltips is also unclear right now - I think adding descriptions to questions inline would be better than relying on tooltips like this.

What are our use cases for tooltips?
- icon descriptions (a la github)
- extra meta information - i.e. "what service applications does this question come from?"

**Comment by bengolder** [comment]
Maybe error messages. But they should probably just be explicitly switched on and off, not based on hover or click.

**Comment by mapsam** [comment]
yes, errors would be good!
