### ISSUE TITLE
Tabs on patient details don't work on mobile

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#85]
ruh roh

**Comment by mapsam** [comment]
@bengolder the buttons seem to be working for me. Do you mean they aren't mobile-friendly?

**Comment by bengolder** [comment]
Just reposting the image from #36 so you can see. They function, but the layout doesn't work:
![image](https://cloud.githubusercontent.com/assets/451510/7738411/d86975be-ff08-11e4-9dc2-6a9e869a0985.png)

**Comment by mapsam** [comment]
Looks like there is no query in bootstrap for making these look different. When we get to the design phase we can make something better :dancer:

**Comment by bengolder** [comment]
Maybe they should just shorten to "Details", "Print", and "History" on mobile.

**Comment by esmithayer** [comment]
#62 should cover this.
