### ISSUE TITLE
How to handle hand-off between services

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#9]
This warrants its own pathway, but there a bunch of ideas floating around about how a client gets from one service to another, and what role the app plays in that.

This would overlap with two other pathways: the end of signing up at the first service, and the beginning of going to the 2nd service.

This touches on who has access to a client's information, and how we decide on the permission to share client info (share with a network of providers vs. individual providers).

Currently, some of the ideas on the table are:
- **Screener-initiated with client consent**:
  - screener at Service A could tell a client that the client is eligible for Service B. 
  - screener could initiate a message that a client can respond to in order to give permission to share info with Service B. 
  - With client's consent, the client shows up in a list of new clients in Service B's interface to the app.
- **phone call with network consent**:
  - Client calls to make an appointment with a new service
  - the new service lets them know that they can use the screening app. 
  - Since client gave network permission previously, the service can already access the client's information
  - new service simply reviews the documents or asks the client to bring in more documents.
- **client-initiated**:
  - Client sees a poster that says they can add the service on their screening app
  - they self-initiate, sharing info with Service B via their mobile phone or other device
  - the client shows up in a list of new clients in Service B's interface to the app.

**Comment by mapsam** [comment]
I'm a fan of a couple of these in particular:

**"With client's consent, the client shows up in a list of new clients in Service B's interface to the app."**  
This seems to be process that involves the least amount of interactions with the application and that can become part of the First-time assistance pathway. The client goes to Service B and as part of the Service B's income verification they would ask if the user wants to be part of the screening application (similar to first-time sign up) and either 1) the client says they already are a part of it or 2) Service B does a search on client's information to find out that their information is already in the screening app, allowing them to approve client immediately.

**"they self-initiate, sharing info with Service B via their mobile phone or other device"**  
This seems like a really powerful _feature_ for the application. I'm interested to hear **how** one would share their information? It seems like it'd be useful to just be able to share in person when they go to Service B or be able to have Service B verify _during_ the time they are booking an appointment so the client is confident they can go to the appointment without their documentation.

**Comment by mapsam** [comment]
It seems that there are _events_ when a user is contacting/arriving at an appointment and these _events_ should always start by asking "are you a part of this program?" then
- client answers **"no"**. service "would you like to join?"
- client answers **"yes"**. service "great, let's check your account."
