### ISSUE TITLE
Make monthly income more explicit and do some calculations for the user/patient.

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#97]
It was way too open, as a number. Without specifying exactly what number you are looking for this question can be confusing. User would like to be able to enter multiple ways depending on what the patient knows, and calculate annual income from it.

Example Options
- Enter hourly wage and hours / week
- Enter amount on weekly or biweekly paystub
- Enter monthly

**Comment by bengolder** [comment]
A simple option would be to include a calculator in the page, like mRelief does, and see if that solves the issue.
![screen shot 2015-05-19 at 9 37 04 am](https://cloud.githubusercontent.com/assets/451510/7708457/a458d4ee-fe0a-11e4-8595-557230c3b69d.png)

**Comment by mapsam** [comment]
This issue came again in a separate user test. I think the calculator is interesting, but it still leaves room for error. What if we had someone select a dropdown of hourly/month/yearly and did the calculation ourselves?
