### ISSUE TITLE
Medicaid question is not as simple as yes/no

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#98]
Having only yes/no for the Medicaid option was difficult. User thinks most people won’t know this question, so potentially having a “maybe” would be good to allow them to get through the form. Some people are eligible for Plan First, which isn’t really that helpful healthcare-wise, but they might not be sure whether that counts as Medicaid for this question.

**Comment by bengolder** [comment]
I vote for adding a "Not Sure" option

**Comment by mapsam** [comment]
+1

This was verified again in user testing this morning

**Comment by bengolder** [comment]
Don't see a yes/no field for medicaid. Could use more clarity on this before fixing.

**Comment by esmithayer** [comment]
We're talking about the Medicaid question on the prescreening page, not in patient details.

**Comment by mapsam** [comment]
Thanks @esmithayer. Sorry @bengolder I assumed this question only existed within the pre-screener. Where else is it?

**Comment by bengolder** [comment]
ooh, I was looking in patient details.

**Comment by mapsam** [comment]
Let's keep this one open since we'll want to update in the server as well to make sure `not sure` evaluates uniquely. Do we think it should be _lenient_ or _strict_?

**Comment by bengolder** [comment]
We should tell them we aren't sure, and then direct them to a place where they can figure it out. In essence, we should deal with these answers the way that Access Now or others would deal with it, which I assume is to refer people to navigators.

**Comment by mapsam** [comment]
Definitely better. We've heard feedback on the pre-screening asking for information as to _why_ and _why aren't_ individuals eligible. Pointing to a navigator sounds great.
