### ISSUE TITLE
Phone number primary label is confusing

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#99]
Let's find something better? We could also look at combining this with the description and remove a field.

**Comment by bengolder** [comment]
I think we should remove it. No phone number needs to be designated as "primary". It was an unsupported assumption I made based on the fact that both forms have multiple phones. There might be a need to prioritize phone numbers or to have clarity on which are cell phones, but "primary" does a poor job of answering these needs.

Daily Planet phones:
![screen shot 2015-05-19 at 9 40 27 am](https://cloud.githubusercontent.com/assets/451510/7708562/5ee6396e-fe0b-11e4-9d03-4c64d1181822.png)

Access Now phones
![screen shot 2015-05-19 at 9 39 51 am](https://cloud.githubusercontent.com/assets/451510/7708563/5ee656ec-fe0b-11e4-8e1e-e16eb736c033.png)
